<nav>
    <ul>
        <li>
            <select onchange="if (this.value) window.location.href=this.value;">
                <option value="">Select a Page...</option>
                <option value="index.php">Home</option>
                <option value="pets.php">Pets</option>
                <option value="gallery.php">Gallery</option>
                <option value="add.php">Add More</option>
            </select>
        </li>
    </ul>
</nav>
